default:
  config:
    data:
      version: v1beta2
      deployments:
        - name: remote-dependency-subpath
          component:
            containers:
              - image: nginx
test:
  config:
    data:
      version: v1beta2
      deployments:
        - name: remote-dependency-subpath-test
          component:
            containers:
              - image: nginx
